language: python
dist: xenial
sudo: false
python:
- '3.6'
- '3.7'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- python setup.py install
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
script:
- pytest --cov=groceries_app groceries_app
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: UJ4TnAvhJf3q+MvcYlZjI/wBqhJB5HDdJucEruTmViNxbzF3HxwcpFLKvSbDnF7qhtKD9W3s89WrnXs7gDhvh0OHf/WCkB5uLlNiepb+MdHBOOLYzOO7rLjfWfb4Ube0yQBgxFxDnDKUBLYvQw67KL6zHGk64kJevLMbZ9Hz04rfsZtrfabka5JSnaWuRKQAv9as3QMSqCkJ+PEE6VgkTvIgwb7ol38YXAQroigVkT15T6tPYJkp2czoIi5yXQqDCRasV0GX4ejNp6igZW1NRTri13ZRpHit/9bD5gzP196rYetByyqqLlmWmy5gAed9yClkV+9diy1EwB62+GV+aPnuvOasm8z+C2Y9YQVJyzaIVEEjjg+eFChaTgTnkauB3JlXkc4M/n8SfNtUh8fAElCn1DaY3YxMebLH3gSgZMVz6Dslubol/QD8T/KZ4hHf8HVZWTmI8BEuQ0EV/+vN5qhV3FRFkZLg2MY++FOxp3hc11LjP73UwItpOlYSpwYTY/dsLJZlPYalghOhewPBXyRscqerbySi3y8CQdbaLz6P8nth8pcB+rqeHFxEecuH9F2L5YCpn/ut8u1Obk9fkp6Hzua46w2o/ea9M9p1W0dRrxesVjt+1CAXAHfs6rUJL1/sNlBTCFLDQsWEgRRmH5KCAjl/7gxStT0U7MwdkK0=
  on:
    branch: master
  skip_existing: true
